export const ROLES = {
  SUPER_ADMIN: 'super_admin',
  ADMIN: 'admin',
  USER: 'user',
};

export const PERMISSIONS = {
  // Super Admin only
  MANAGE_PLATFORM: 'MANAGE_PLATFORM',
  MANAGE_ADMINS: 'MANAGE_ADMINS',
  MANAGE_ROLES: 'MANAGE_ROLES',
  
  // Admins
  MANAGE_USERS: 'MANAGE_USERS',
  MANAGE_SUBSCRIPTIONS: 'MANAGE_SUBSCRIPTIONS',
  VIEW_ANALYTICS: 'VIEW_ANALYTICS',
  MANAGE_AI: 'MANAGE_AI',
  MANAGE_SUPPORT: 'MANAGE_SUPPORT',
  MODERATE_COMMUNITY: 'MODERATE_COMMUNITY',
  MANAGE_DESTINATIONS: 'MANAGE_DESTINATIONS',
  MANAGE_ACTIVITIES: 'MANAGE_ACTIVITIES',
  MANAGE_PACKAGES: 'MANAGE_PACKAGES',
  PUBLISH_PACKAGES: 'PUBLISH_PACKAGES',
  RESPOND_TO_TRAVELERS: 'RESPOND_TO_TRAVELERS',
  
  // Users
  UNLIMITED_TRIPS: 'UNLIMITED_TRIPS',
  ADVANCED_AI: 'ADVANCED_AI',
  TRIP_SHARING: 'TRIP_SHARING',
  CREATE_TRIP: 'CREATE_TRIP',
  VIEW_PUBLIC_TRIPS: 'VIEW_PUBLIC_TRIPS',
};

export const ROLE_PERMISSIONS = {
  [ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS), // Has all permissions
  
  [ROLES.ADMIN]: [
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.MANAGE_SUBSCRIPTIONS,
    PERMISSIONS.VIEW_ANALYTICS,
    PERMISSIONS.MANAGE_AI,
    PERMISSIONS.MANAGE_SUPPORT,
    PERMISSIONS.MODERATE_COMMUNITY,
    PERMISSIONS.MANAGE_DESTINATIONS,
    PERMISSIONS.MANAGE_ACTIVITIES,
    PERMISSIONS.MANAGE_PACKAGES,
    PERMISSIONS.PUBLISH_PACKAGES,
    PERMISSIONS.RESPOND_TO_TRAVELERS,
    PERMISSIONS.UNLIMITED_TRIPS,
    PERMISSIONS.ADVANCED_AI,
    PERMISSIONS.TRIP_SHARING,
    PERMISSIONS.CREATE_TRIP,
    PERMISSIONS.VIEW_PUBLIC_TRIPS,
  ],
  
  [ROLES.USER]: [
    PERMISSIONS.UNLIMITED_TRIPS, // You can decide to scope this later, but for now we combined users
    PERMISSIONS.ADVANCED_AI,
    PERMISSIONS.TRIP_SHARING,
    PERMISSIONS.CREATE_TRIP,
    PERMISSIONS.VIEW_PUBLIC_TRIPS,
  ],
};
